# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

# extra settings to be merged into OpenTelemetry Collector configuration
# do not delete this file
receivers:
  # Prometheus receiver to scrape metrics from Prometheus-compatible endpoints
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: ['localhost:8888']

exporters:
  otlphttp/oodle:
    headers:
      X-API-KEY: ${env:OODLE_API_KEY}
      X-OODLE-INSTANCE: ${env:OODLE_INSTANCE}
    traces_endpoint: https://${env:OODLE_INSTANCE}.collector.oodle.ai/v1/otlp/traces
    metrics_endpoint: https://${env:OODLE_INSTANCE}.collector.oodle.ai/v1/otlp/metrics/${env:OODLE_INSTANCE}
    logs_endpoint: https://${env:OODLE_INSTANCE}-logs.collector.oodle.ai/ingest/otel/v1/logs
  
  prometheusremotewrite/oodle:
    endpoint: https://${env:OODLE_INSTANCE}.collector.oodle.ai/v1/prometheus/${env:OODLE_INSTANCE}/write
    headers:
      X-API-KEY: ${env:OODLE_API_KEY}
  
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, transform, batch]
      exporters: [otlphttp/oodle, spanmetrics]
    metrics:
      receivers: [httpcheck/frontend-proxy, hostmetrics, nginx, otlp, postgresql, redis, spanmetrics]
      processors: [resourcedetection, memory_limiter, batch]
      exporters: [otlphttp/oodle]
    metrics/prom:
      receivers: [prometheus]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite/oodle]
    logs:
      receivers: [otlp]
      processors: [resourcedetection, memory_limiter, batch]
      exporters: [otlphttp/oodle]
  # Telemetry configuration to expose Prometheus metrics
  telemetry:
    metrics:
      level: detailed
      readers:
        - pull:
            exporter:
              prometheus:
                host: '0.0.0.0'
                port: 8888


## Example configuration for sending data to your own OTLP HTTP backend
## Note: the spanmetrics exporter must be included in the exporters array
## if overriding the traces pipeline.
##
#  exporters:
#    otlphttp/example:
#      endpoint: <your-endpoint-url>
#
#  service:
#    pipelines:
#      traces:
#        exporters: [spanmetrics, otlphttp/example]
